services:
  - type: web
    name: cashbook
    runtime: node
    plan: free
    buildCommand: npm install && cd client && npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:***REDACTED_DB_PASSWORD***@db.ndnkndazxvwrajdqklof.supabase.co:5432/postgres
      - key: JWT_SECRET
        value: ***REDACTED_JWT_SECRET***
      - key: NODE_ENV
        value: production
